[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flappybird-monorepo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flappy-bird-gymnasium",
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "pre-commit>=4.0.1",
    "pytest>=8.3.4",
    "tqdm>=4.67.1",
]

[tool.setuptools.packages.find]
where = ["flappybird"]

[tool.ruff]
line-length = 100

[tool.uv.sources]
flappy-bird-gymnasium = { path = "../flappy-bird-gymnasium", editable = true }
