# Model Configuration
checkpoint_path: null

model:
  train_freq: 1
  gradient_steps: 1
  exploration_fraction: 0.1
  exploration_initial_eps: 0.0001
  exploration_final_eps: 0.0001
  tensorboard_log: "./logs/tensorboard/"

# Training Configuration
training:
  total_timesteps: 30_000_000  # 30M steps
  tb_log_name: "dqn_flappybird_v1"
  reset_num_timesteps: true
