# Model Configuration
model:
  train_freq: 4
  gradient_steps: 1
  exploration_fraction: 0.1
  exploration_final_eps: 0.01
  tensorboard_log: "./logs/tensorboard/"

# Training Configuration
training:
  total_timesteps: 10_000_000  # 10M steps

# Evaluation Configuration
evaluation:
  eval_freq: 1_000_000       # Evaluate every 1M steps
  n_eval_episodes: 100      # Number of episodes for evaluation
  save_path: "./logs/best_model/"