name: &name dqn_flappybird_v6
checkpoint_path: null

env:
  id: FlappyBird-v0
  use_lidar: false
  score_limit: 1000
  render_mode: null

model:
  policy: MlpPolicy
  train_freq: 1
  gradient_steps: 1
  exploration_fraction: 0.1
  exploration_initial_eps: 0.0001
  exploration_final_eps: 0.0001
  tensorboard_log: "./logs/tensorboard/"
  policy_kwargs:
    net_arch: [64, 64]
  buffer_size: 100
training:
  total_timesteps: 5_000  # 30M steps
  tb_log_name: *name
  reset_num_timesteps: true

checkpoint:
  save_freq: 100_000
  save_path: data
  name_prefix: *name
